### ISSUE TITLE
Where can I find the code?

### ISSUE THREAD

**Issue by kyoungrok0517** [dschaehi/capturing-word-order#1]
Hello. I came to this place by following the link in your paper. I hope the actual code is uploaded soon :) thanks

**Comment by kyoungrok0517** [comment]
One more, is your embedding different from DisC embedding introduced by S. Arora (http://www.offconvex.org/2018/06/25/textembeddings/)? I didn't read your paper in detail yet, but it'll be helpful if I could have author-directed keypoints to have in mind when reading.

**Comment by dschaehi** [comment]
Hi, the code to replicate the results are now online. You can check my talk at ECAI 2020 (https://digital.ecai2020.eu) to get an idea of the paper. Attending ECAI 2020 is free.
